repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.1
    hooks:
      - id: commitizen
        name: commitizen
        stages: [commit-msg]

  - repo: https://github.com/conventional-changelog/commitlint
    rev: v17.6.0
    hooks:
      - id: commitlint
        name: commitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
      - id: eslint
        name: eslint
        files: '\.(js|ts|jsx|tsx)$'
