version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: specflow
      POSTGRES_PASSWORD: specflow
      POSTGRES_DB: specflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: specflow-backend:local
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/specflow
      SPRING_DATASOURCE_USERNAME: specflow
      SPRING_DATASOURCE_PASSWORD: specflow
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: specflow-frontend:local
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
