version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: specflow
      POSTGRES_PASSWORD: specflow
      POSTGRES_DB: specflow
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://specflow:specflow@postgres:5432/specflow
    depends_on:
      - postgres

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "yarn install --frozen-lockfile && yarn start"
    ports:
      - 4200:4200
    depends_on:
      - backend

volumes:
  pgdata:
