name: Commitlint feedback

on:
  workflow_run:
    workflows: ["Quality checks"]
    types: [completed]

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Post PR comment when commitlint failed
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = github.context.payload.workflow_run
            if (!run) return
            const pr = run.pull_requests && run.pull_requests[0]
            if (!pr) return
            const body = `Hello! The commit message checks failed on this PR. Please ensure commit messages follow Conventional Commits as described in CONTRIBUTING.md. You can run locally with:\n\n\t./scripts/setup-dev.sh\n\nSee https://www.conventionalcommits.org/ for the format.`
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            })
