name: Commitlint feedback

on:
  workflow_run:
    workflows: ["Quality checks"]
    types: [completed]

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '18'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache commitlint node_modules
        uses: actions/cache@v4
        with:
          path: ./.commitlint_tmp/node_modules
          key: commitlint-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('commitlint.config.js') }}
          restore-keys: |
            commitlint-${{ runner.os }}-node-

      - name: Install commitlint temporarily
        run: |
          TMPDIR="$(pwd)/.commitlint_tmp"
          mkdir -p "$TMPDIR"
          pushd "$TMPDIR"
          npm init -y >/dev/null 2>&1 || true
          # Install only if node_modules is missing or incomplete; cache will speed this up on hits
          npm install --no-save @commitlint/config-conventional @commitlint/cli >/dev/null 2>&1 || true
          popd

      - name: Run commitlint and save output
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          set -euo pipefail
          BIN="./.commitlint_tmp/node_modules/.bin/commitlint"
          PAYLOAD=$(cat "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(echo "$PAYLOAD" | jq -r '.workflow_run.pull_requests[0].number // empty')
          FROM=$(echo "$PAYLOAD" | jq -r '.workflow_run.base_sha')
          TO=$(echo "$PAYLOAD" | jq -r '.workflow_run.head_sha')
          echo "PR=$PR_NUMBER FROM=$FROM TO=$TO" > commitlint_output.txt
          if [ -n "$PR_NUMBER" ] && [ -x "$BIN" ]; then
            "$BIN" --from="$FROM" --to="$TO" 2>&1 | sed -n '1,4000p' >> commitlint_output.txt || true
          else
            echo "commitlint binary not found or no PR" >> commitlint_output.txt
          fi

      - name: Post PR comment with commitlint output
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const run = context.payload.workflow_run;
            if (!run) return;
            const prs = run.pull_requests || [];
            if (!prs || prs.length === 0) return;
            const prNumber = prs[0].number;
            const output = fs.readFileSync('commitlint_output.txt', 'utf8').slice(0, 4000);
            const bodyLines = [
              'Hello! The commit message checks failed on this PR.',
              '',
              'commitlint output (truncated):',
              '```',
              output,
              '```',
              '',
              'You can reproduce locally by running:',
              './scripts/setup-dev.sh',
              `./.commitlint_tmp/node_modules/.bin/commitlint --from=${run.base_sha} --to=${run.head_sha}`,
              '',
              'See CONTRIBUTING.md for the required format.'
            ];
            const body = bodyLines.join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body,
            });
